# Generated by Django 3.2.16 on 2022-10-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='fname',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='lname',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
