# Generated by Django 3.2.16 on 2022-11-12 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20221112_1058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Address_Book',
        ),
    ]
