# Generated by Django 3.2.16 on 2022-11-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_userprofile_address_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='address_book',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address_book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
