# Generated by Django 3.2.16 on 2022-11-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimnesions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
