# Generated by Django 3.2.16 on 2022-11-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_other_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_product',
            name='images',
            field=models.ImageField(upload_to='view/photos'),
        ),
    ]
