# Generated by Django 3.2.16 on 2022-11-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0015_auto_20221113_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
