# Generated by Django 3.2.16 on 2022-11-18 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0017_auto_20221113_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='design',
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(blank=True, choices=[('color', 'color'), ('size', 'size')], max_length=100),
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='variation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.product'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Design',
        ),
    ]
