# Generated by Django 3.2.16 on 2022-11-22 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0002_dimnesions'),
        ('shop_app', '0020_auto_20221122_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='variations.dimnesions'),
        ),
    ]
