# Generated by Django 3.2.16 on 2023-02-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0021_product_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display2',
            field=models.ImageField(default='a3.png', upload_to='photos/display'),
        ),
    ]
