# Generated by Django 3.2.16 on 2023-03-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0024_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='description',
        ),
    ]
