# Generated by Django 3.2.16 on 2023-03-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='reserved_until',
            field=models.DateTimeField(null=True),
        ),
    ]
